### ISSUE TITLE
genrand64_res53() does not provide 53 significant bits

### ISSUE THREAD

**Issue by vigna** [sharase/melg-64#1]
The bit trick used by genrand64_res53() and genrand64_res53_open() generates only 52 significant bits of the 53 available in the IEEE floating-point representation. This is immediately visible, as

    (genrand64_int64() >> 12)

keeps just 52 bits. The function names are misleading at best.

It would be better to have  genrand64_res53() returning, correctly, something like

    (genrand64_int64() >> 11) * 0x1.0p-53;

and then have a genrand64_fast_res52() function returning just 52 bits, so the users can decide whether they want to lose half of the floating-point values or not.

**Comment by sharase** [comment]
Excuse me for my late response.
Thank you for pointing out the issue.

Now, I am planning to create a webpage to explain the results of my recent research work.
I would like to read the PRNG shootout at your website carefully and fix the functions by following your suggestion.

**Comment by sharase** [comment]
I fixed it. 
Please let me know if you have any problems.
