### ISSUE TITLE
is genrand64_real1() really uniform?

### ISSUE THREAD

**Issue by jherekhealy** [sharase/melg-64#4]
I was wondering if the generated numbers in [0,1] were really uniform. I am wondering in particular since we divide by 2^53-1 but discard only 11 bits.

0 (int) maps to 0 (double)
2^53 - 1 (int) maps to 1 (double)
2^53 - 2 (int) maps to 1 (double)
2^53 - 3 (int) maps to 1- 1/2^53 (double)
2^53 - 4 (int) maps to 1- 2/2^53 (double)
...

I may be wrong but it looks like 1 is over-represented by 1 number (the transformation is not a bijection). Of course, this is hardly an issue in practice, more of a curiosity.

**Comment by jherekhealy** [comment]
For example, 
((x >> 12 )+0.5)  / 4503599627370495.0 -0.5/4503599627370495.0
would lead to two 0s and two 1s, actually two of each (symmetric mapping), although we lose one bit in a similar fashion as the open interval mapping. If we consider powers 2^52, it would be one of each.

This may be written more efficiently.

**Comment by sharase** [comment]
Thank you for your comments.
I would like to take the time to think about the issue a little bit.
In fact, I use the same functions as the 64-bit Mersenne Twister.
So, I would like to consult Prof.  Matsumoto, Nishimura, and Saito, who developed Mersenne Twisters.
Could you kindly wait for a couple of days?

**Comment by sharase** [comment]
I’m sorry for late response.
I had thought about the above conversion method, but it seems to be difficult to divide integers in [0, 2^64-1] into double-precision floating numbers in [0, 1] truly equally distributed, very quickly. 
At this moment, I think the use of the function genrand64_fast_res52_open() that generates a random number on (0,1)-real-interval using a union trick should be recommended. 

I’m thinking about whether to write the issue in the code.

**Comment by sharase** [comment]
I think there is no big issue, so I would like to close it at this time. 
Thank you very much for your suggestion.
